apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2i3u
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-2i3u@sha256:8161e4c89c3bcc5ce01956b34ae27e521ad4636bf2ca1ada2b2e6f2c4ae17623
        name: my-nodejs
        resources: {}
status: {}
